/* Generated by caption-bake/scripts/publish-to-pages.sh — do not edit by hand. */
window.CAPTIONBAKE_RELEASE = {
  version: "0.1.0",
  arm64: "https://releases.corelogic.cc/captionbake/latest.dmg",
  tipUrl: "https://github.com/sponsors/CORE-LOGIC-LLC-AZ",
};

(function applyReleaseConfig() {
  var cfg = window.CAPTIONBAKE_RELEASE;
  if (!cfg) return;
  var arm = document.getElementById("download-arm");
  if (arm) arm.setAttribute("href", cfg.arm64);
})();
